### ISSUE TITLE
Internação Paciente

### ISSUE THREAD

**Issue by WMCOSTA** [rogrs/safh#18]
A tela de internação fara uso dos dados cadastrais atraves das opções de busca para cada entidade relacionada conforme abaixo:

Paciente, Medico, Clínica, Diagnostico, PrescricaoMedica.

Os campos Evolução, observação e medicao do paciente são texto livre inseridos pelos médicos.

Cada linha da prescrição deve conter botão de busca para permitir o usuário selecionar uma prescrição, caso ele queira uma já existente e um botão que redireciona para o cadastro de prescrição para ele criar uma nova.

As medições são taxas numéricas obtidas diariamente do paciente que estão relacionadas prescrição do dia.

**Comment by WMCOSTA** [comment]
CORREÇÃO!!!!!

NAO INCLUIR OS DADOS DAS TAXAS de medição nesse formulário.

NAO CONSIDERE POR ENQUANTO AO DADOS DA MEDIÇÃO DAS TAXAS. IREMOS INSERIR-LOS NUM OUTRO MOMENTO PELO ENFERMEIRO.

**Comment by rogrs** [comment]
Alterações realizadas
