### ISSUE TITLE
Internação Paciente

### ISSUE THREAD

**Issue by WMCOSTA** [rogrs/safh#20]
Erro na criação. Siga os passo abaixo:

1 - Clicar no botão "Criar uma nova Internação" 
2 - Selecione uma data no campo "Data Internação"
3 - Clique no botão "Salvar"

**Comment by rogrs** [comment]
Não  foram definidas nenhuma regra de negocio:

Nessa fase pode realizar tudo


Se quiser eu torno obrigatorio o preenchimento dos campos

**Comment by WMCOSTA** [comment]
Nesse momento não temos regras definidas pelo usuário. devemos manter as telas com o minimo possível de comportamento funcional, possibilitando uma  navegação sem erro.
