### ISSUE TITLE
Prescrição Paciente

### ISSUE THREAD

**Issue by WMCOSTA** [rogrs/safh#21]
No cadastro de prescrição não devemos relacionar/exibir o paciente. Após criarmos a prescrição, ela ficará disponível para seleção na tela de internação. Somente nesse momento, ela irá se relacionar ao paciente internado.

**Comment by rogrs** [comment]
Prescrição se relaciona com quem então?

Pra que serve uma prescrição sem Paciente???

**Comment by WMCOSTA** [comment]
Prescrição de Paciente se relaciona com quem então?
R: A prescrição será relacionada ao Paciente somente no momento da internação. Ou seja, quando estivermos tratando/prescrevendo remédios para um paciente internado.

Pra que serve uma Prescrição sem Paciente???
R: Se tratarmos de forma independente, a mesma prescrição poderá ser usada para ser usada em outros pacientes internados.

Ou vc quer um cadastro de Prescrições Génericas?
R: Sim. Você não acha?
