### ISSUE TITLE
Exclusão de pacientes

### ISSUE THREAD

**Issue by WMCOSTA** [rogrs/safh#24]
Erro na exclusão do paciente

![exclusaopac](https://cloud.githubusercontent.com/assets/19366629/15842034/eacb76fc-2c2b-11e6-9320-52af186908be.png)

**Comment by rogrs** [comment]
Foi adicionado exclusão em cascata  a todos os cadastros com relacionamentos.

Ao excluir o cadastro principal as informções relacionadas a este serão excluídas também
